HOST: http://api.visualfeature.com/

--- Visual Feature API ---
---
Managing lifecycle of a feature from idea to implementation and deployment.
---

--
Accounts Resources
The following is a section of resources related to app accounts.
--
List accounts (only for admin access).
GET /accounts
< 200
< Content-Type: application/json
{
    "accounts": [
        {
            "id": 1,
            "url": "/accounts/1",
            "name": "Naviam",
            "status": "active",
            "description": "Naviam company account"
        },
        {
            "id": 2,
            "url": "/accounts/2",
            "name": "ServiceChannel",
            "status": "active",
            "description": "ServiceChannel company account"
        }
    ]
}

Get single account by id.
GET /accounts/2
< 200
< Content-Type: application/json
{
    "id": 2,
    "url": "/accounts/2",
    "name": "ServiceChannel",
    "status": "active",
    "description": "ServiceChannel company account"
}

Create new app account.
POST /accounts
> Content-Type: application/json
{
    "name": "eLifeLab",
    "description": "eLifeLab company account"
}
< 201
< Content-Type: application/json
< Location: "/accounts/3"
{
    "id": 3,
    "status": "pending confirmation"
}

Update account name / description
PUT /accounts/2
> Content-Type: application/json
{
    "name": "ServiceChannel2",
    "description": "test account"
}
< 200
< Content-Type: application/json
< Location: "/accounts/2"
{
    "id": 2
}

Remove account (close).
DELETE /accounts/3
< 200
{
    "id": 3,
    "status": "removed"
}

--
Account Users Resources
The following is a section of resources related to the account users. An idea is that more than one user can have access to service account.
--

List account users
GET /accounts/2/users
< 200
< Content-Type: application/json
{
    "users": [
        { "id": 1, "email": "vhatalski@naviam.com" },
        { "id": 2, "email": "alex@servicechannel.com" }
    ]
}

Get single user
GET /accounts/2/users/1
< 200
< Content-Type: application/json
{
    "id": 2, 
    "email": "alex@servicechannel.com"
}

Add new user to account
POST /accounts/2/users
> Content-Type: application/json
{
    "email": "pmironchik@naviam.com",
    "password": "245t4t45"
}
< 201
< Content-Type: application/json
< Location: "/accounts/2/users/3"
{ "id": 3 }

Remove user from account
DELETE /accounts/2/users/3
< 204
< Content-Type: application/json
{}

--
Stages Resources
The following is a section of resources related to the states / stages feature should go through in it's life.
--
List stages.
GET /stages
< 200
< Content-Type: application/json
{ "stages": [
{ "name": "R&D", "branch": "dev", "project": "ServiceChannel", "id": 1, "url": "/stages/1"},
{ "name": "QA1", "branch": "qa1", "project": "ServiceChannel", "id": 2, "url": "/stages/2"},
{ "name": "QA2", "branch": "qa2", "project": "ServiceChannel", "id": 3, "url": "/stages/3"},
{ "name": "LoadTests", "branch": "load", "project": "ServiceChannel", "id": 4, "url": "/stages/4"},
{ "name": "Sandbox1", "branch": "sb1", "project": "ServiceChannel", "id": 5, "url": "/stages/5"},
{ "name": "Sandbox2", "branch": "sb2", "project": "ServiceChannel", "id": 6, "url": "/stages/6"},
{ "name": "Staging", "branch": "master", "project": "ServiceChannel", "id": 7, "url": "/stages/7"},
{ "name": "Production", "branch": "master", "project": "ServiceChannel", "id": 8, "url": "/stages/8"}
] }

Add new stage
POST /stages
> Content-Type: application/json
{
    "name":"Sandbox3",
    "branch": "sb3",
    "project": "ServiceChannel"
}
< 201
< Content-Type: application/json
< Location: "/stages/9"
{ "id": 9 }

PUT /stages/2
> Content-Type: application/json
{ "branch": "sandbox3" }
< 200
< Content-Type: application/json


--
Feature State Resources
The following is a section of resources related to the state of the feature
--
List features in a particular state. (comment block again in Markdown)
GET /features
< 200
< Content-Type: application/json
{
    "features": [
    {
        "id": 1,
        "url": "/features/1",
        "stage_url": "/stages/1",
        "story_url": "/stories/1",
        "pull_request_url": "/pullrequests/1"
        "title": "My first feature",
        "description": "what should be done"
    },
    {
        "id": 2,
        "url": "/features/2",
        "stage_url": "/stages/1",
        "story_url": "/stories/2",
        "pull_request_url": "/pullrequests/2"
        "title": "My second feature",
        "description": "what should be done"
    }]
}

Add new feature
POST /features
> Content-Type: application/json
{
    "title":"1AB23ORM",
    "description": "2"
}
< 201
< Content-Type: application/json
< Location: /features/3
{ "id": 3}


-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }