HOST: http://api.visualfeature.com/

--- Visual Feature API ---
---
Managing lifecycle of a feature from idea to implementation and deployment.
---

--
Stages Resources
The following is a section of resources related to the states / stages feature should go through in it's life.
--
List stages.
GET /stages
< 200
< Content-Type: application/json
{ "stages": [
{ "environment": "Development", "branch": "dev", "project": "ServiceChannel", "id": 1},
{ "environment": "QA1", "branch": "qa1", "project": "ServiceChannel", "id": 2},
{ "environment": "QA2", "branch": "qa2", "project": "ServiceChannel", "id": 3},
{ "environment": "Sandbox1", "branch": "master", "project": "ServiceChannel", "id": 4},
{ "environment": "Sandbox2", "branch": "master", "project": "ServiceChannel", "id": 5},
{ "environment": "Staging", "branch": "staging", "project": "ServiceChannel", "id": 6},
{ "environment": "Production", "branch": "master", "project": "ServiceChannel", "id": 7}
] }


--
Feature State Resources
The following is a section of resources related to the state of the feature
--
List features in a particular state. (comment block again in Markdown)
GET /features
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }


Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }


-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }